import {ArrowUpRight,GitCommitHorizontal,GitBranch,RefreshCw,Users,AlertCircle,FolderGit2} from 'lucide-react';import {Link} from 'react-router-dom';import {Button,Avatar,Badge} from '../../../../packages/ui/src/index';import type {Activity,Repository} from '../../../../packages/shared/src/index';import {relative} from '../lib/api';
export function PageHeading({eyebrow,title,description,action}:{eyebrow?:string;title:string;description:string;action?:React.ReactNode}){return <div className="page-heading"><div>{eyebrow&&<div className="eyebrow">{eyebrow}</div>}<h1>{title}</h1><p>{description}</p></div>{action}</div>;}
export function Loading(){return <div className="skeleton-wrap" aria-label="Loading workspace"><div className="skeleton skeleton-title"/><div className="stats-grid">{[1,2,3,4].map(i=><div key={i} className="skeleton skeleton-card"/>)}</div><div className="skeleton skeleton-panel"/></div>;}
export function ErrorState({error,retry}:{error:Error;retry:()=>unknown}){return <div className="empty-state"><AlertCircle size={32}/><h3>We couldn’t load this workspace</h3><p>{error.message}</p><Button onClick={()=>retry()}>Try again</Button></div>;}
export function Empty({title,description,action}:{title:string;description:string;action?:React.ReactNode}){return <div className="empty-state"><FolderGit2 size={32}/><h3>{title}</h3><p>{description}</p>{action}</div>;}
export function ActivityList({events,compact=false}:{events:(Activity&{repoName?:string;repoId?:string})[];compact?:boolean}){return <div className={`activity-list ${compact?'compact':''}`}>{events.map((e,i)=>{const Icon=e.type==='commit'?GitCommitHorizontal:e.type==='branch'?GitBranch:e.type==='member'?Users:RefreshCw;return <div className="activity-item" key={e.id}><div className={`event-icon event-${e.type}`}><Icon size={15}/></div><div className="activity-copy"><div><strong>{e.author}</strong> <span className="muted">{e.type==='commit'?'pushed a commit':e.type==='sync'?'completed a sync':'updated the workspace'}</span></div><p>{e.message}</p>{e.repoName&&<Link className="activity-repo" to={`/repositories/${e.repoId}`}>{e.repoName}</Link>}</div><time>{relative(e.createdAt)}</time></div>;})}</div>;}
export function People({repo}:{repo:Repository}){return <div className="avatar-stack">{repo.members.slice(0,4).map((m,i)=><Avatar key={m.id} name={m.name} index={i} size="small"/>)}</div>;}
export function PanelTitle({title,extra}:{title:string;extra?:React.ReactNode}){return <div className="panel-title"><h3>{title}</h3>{extra}</div>;}
export function ViewLink({to,children='View all'}:{to:string;children?:React.ReactNode}){return <Link to={to} className="subtle-link">{children}<ArrowUpRight size={14}/></Link>;}
export {Button,Avatar,Badge};
