import express,{type Request,type Response,type NextFunction} from 'express';
import cors from 'cors';import helmet from 'helmet';import cookieParser from 'cookie-parser';import rateLimit from 'express-rate-limit';import jwt from 'jsonwebtoken';import {hash,compare} from 'bcryptjs';import {randomUUID} from 'node:crypto';import {z} from 'zod';
import {repositorySchema,settingsSchema,branchNameSchema,commitSchema,type Repository,type State,type User} from '../../../packages/shared/src/index';
import {VcsError,createCommit,persistObjects,DiskStorage,mergeCheck,fastForward,rebase,addActivity,ancestors} from '../../../packages/vcs-core/src/index';
import {makeRepository} from './seed';import type {Store} from './store';import {MetadataCache} from './cache';
type Authed=Request & {userId:string;sessionId:string};
const wrap=(fn:(req:Request,res:Response)=>unknown)=> (req:Request,res:Response,next:NextFunction)=>Promise.resolve(fn(req,res)).catch(next);
const authSchema=z.object({email:z.string().email().transform(v=>v.toLowerCase()),password:z.string().min(10).max(128)});
export function createApp(store:Store,options:{secret:string;demo:boolean;origin?:string;storagePath?:string;onChange?:(repoId:string)=>void;cache?:MetadataCache}){
 const app=express(),cache=options.cache??new MetadataCache(),storage=new DiskStorage(options.storagePath??process.env.OBJECT_STORAGE_PATH??'../../data/objects');
 app.disable('x-powered-by');app.use(helmet());app.use(cors({origin:options.origin??'http://localhost:5173',credentials:true}));app.use(express.json({limit:'12mb'}));app.use(cookieParser());
 app.use('/api',(req,res,next)=>{if(!['GET','HEAD','OPTIONS'].includes(req.method)&&req.headers.origin&&req.headers.origin!==(options.origin??'http://localhost:5173')){res.status(403).json({error:'Origin not allowed'});return;}next();});
 app.get('/api/health',(_req,res)=>res.json({data:{status:'ok',demo:options.demo,storage:process.env.STORAGE_DRIVER??'demo'}}));
 app.use('/api/auth',rateLimit({windowMs:60000,limit:30,standardHeaders:'draft-7',legacyHeaders:false}));
 async function session(res:Response,user:User){const id=randomUUID(),expiresAt=new Date(Date.now()+7*86400000).toISOString();await store.mutate(s=>{s.sessions=s.sessions.filter(v=>new Date(v.expiresAt).getTime()>Date.now());s.sessions.push({id,userId:user.id,expiresAt});});const token=jwt.sign({sub:user.id,sid:id},options.secret,{expiresIn:'7d'});res.cookie('velocity_session',token,{httpOnly:true,secure:process.env.NODE_ENV==='production',sameSite:'lax',maxAge:7*86400000,path:'/'});return token;}
 const publicUser=({passwordHash:_,...u}:User)=>u;
 app.post('/api/auth/register',wrap(async(req,res)=>{const input=authSchema.extend({name:z.string().trim().min(2).max(80)}).parse(req.body),passwordHash=await hash(input.password,12);const user=await store.mutate(s=>{if(s.users.some(u=>u.email===input.email))throw new VcsError('An account with this email already exists',409);const user={id:randomUUID(),name:input.name,email:input.email,passwordHash};s.users.push(user);return user;});await session(res,user);res.status(201).json({data:publicUser(user)});}));
 app.post('/api/auth/login',wrap(async(req,res)=>{const input=authSchema.parse(req.body),user=store.read().users.find(u=>u.email===input.email);if(!user||!await compare(input.password,user.passwordHash))throw new VcsError('Email or password is incorrect',401);const token=await session(res,user);res.json({data:{...publicUser(user),...(req.body.cli===true?{token}:{})}});}));
 app.post('/api/auth/demo',wrap(async(_req,res)=>{if(!options.demo)throw new VcsError('Demo access is disabled',403);const user=store.read().users.find(u=>u.email==='demo@velocity.dev');if(!user)throw new VcsError('Demo workspace is not seeded',404);await session(res,user);res.json({data:publicUser(user)});}));
 app.post('/api/auth/forgot',(_req,res)=>res.status(501).json({error:'Email delivery is not configured. Contact your workspace owner to recover access.'}));
 app.use('/api',(req,res,next)=>{try{const token=req.cookies.velocity_session??req.headers.authorization?.replace(/^Bearer /,'');const payload=jwt.verify(token,options.secret) as {sub:string;sid:string};const s=store.read();if(!s.sessions.some(v=>v.id===payload.sid&&v.userId===payload.sub&&new Date(v.expiresAt).getTime()>Date.now()))throw new Error();(req as Authed).userId=payload.sub;(req as Authed).sessionId=payload.sid;next();}catch{res.status(401).json({error:'Please sign in to continue'});}});
 app.get('/api/auth/me',(req,res)=>res.json({data:publicUser(store.read().users.find(u=>u.id===(req as Authed).userId)!)}));
 app.post('/api/auth/logout',wrap(async(req,res)=>{await store.mutate(s=>{s.sessions=s.sessions.filter(v=>v.id!==(req as Authed).sessionId);});res.clearCookie('velocity_session',{path:'/'});res.json({data:{ok:true}});}));
 function access(state:State,req:Request,write=false,admin=false){const r=state.repositories.find(r=>r.id===req.params.id);if(!r)throw new VcsError('Repository not found',404);const member=r.members.find(m=>m.userId===(req as Authed).userId);if(!member&&r.visibility!=='public')throw new VcsError('Repository not found',404);if(write&&(!member||member.role==='Viewer'))throw new VcsError('Write access required',403);if(admin&&(!member||!['Owner','Maintainer'].includes(member.role)))throw new VcsError('Maintainer access required',403);if(write&&r.archived&&!admin)throw new VcsError('This repository is archived',409);return r;}
 function currentUser(s:State,req:Request){return s.users.find(u=>u.id===(req as Authed).userId)!;}
 async function change(req:Request,res:Response,fn:(r:Repository,s:State)=>unknown|Promise<unknown>,admin=false){const result=await store.mutate(async s=>{const r=access(s,req,true,admin),result=await fn(r,s);r.updatedAt=new Date().toISOString();return result??r;});await cache.clear();options.onChange?.(req.params.id);res.json({data:result});}
 app.get('/api/repositories',(req,res)=>res.json({data:store.read().repositories.filter(r=>r.visibility==='public'||r.members.some(m=>m.userId===(req as Authed).userId))}));
 app.post('/api/repositories',wrap(async(req,res)=>{const input=repositorySchema.parse(req.body);const r=await store.mutate(s=>{const user=currentUser(s,req);if(s.repositories.some(r=>r.ownerId===user.id&&r.name===input.name))throw new VcsError('Repository name already exists',409);const r=makeRepository(input.name,user,{description:input.description,visibility:input.visibility,language:input.language,settings:input.settings});r.branches[0].name=branchNameSchema.parse(input.defaultBranch);if(input.defaultBranch==='develop')r.branches[1].name='main';addActivity(r,'repository','Created repository',user.name);s.repositories.push(r);return r;});res.status(201).json({data:r});}));
 app.get('/api/repositories/:id',wrap((req,res)=>res.json({data:access(store.read(),req)})));
 app.patch('/api/repositories/:id',wrap((req,res)=>change(req,res,(r,s)=>{const input=repositorySchema.pick({name:true,description:true,visibility:true}).partial().extend({archived:z.boolean().optional()}).parse(req.body);if(input.name&&s.repositories.some(o=>o.id!==r.id&&o.ownerId===r.ownerId&&o.name===input.name))throw new VcsError('Repository name already exists',409);Object.assign(r,input);addActivity(r,'settings','Updated repository settings',currentUser(s,req).name);},true)));
 app.delete('/api/repositories/:id',wrap(async(req,res)=>{await store.mutate(s=>{const r=access(s,req,true,true);if(r.ownerId!==(req as Authed).userId)throw new VcsError('Only the owner can delete a repository',403);if(req.body.confirm!==r.name)throw new VcsError('Type the repository name to confirm');s.repositories=s.repositories.filter(v=>v.id!==r.id);});res.json({data:{ok:true}});}));
 app.get('/api/repositories/:id/files',wrap(async(req,res)=>{const r=access(store.read(),req),branch=r.branches.find(b=>b.name===(req.query.branch??r.branches.find(b=>b.isDefault)?.name));if(!branch)throw new VcsError('Branch not found',404);const key=`files:${r.id}:${branch.currentHead}`;let files=await cache.get(key);if(!files){files=r.commits.find(c=>c.id===branch.currentHead)?.files??{};await cache.set(key,files,r.settings.cacheTTL);}res.json({data:files});}));
 app.get('/api/repositories/:id/files/*',wrap((req,res)=>{const r=access(store.read(),req);let path=req.params[0];if(path.endsWith('/history')){path=path.slice(0,-8);res.json({data:r.commits.filter(c=>c.changedPaths.includes(path)).map(c=>({...c,files:undefined}))});return;}const head=r.branches.find(b=>b.name===(req.query.branch??r.branches.find(b=>b.isDefault)?.name))?.currentHead;const file=r.commits.find(c=>c.id===head)?.files[path];if(!file)throw new VcsError('File not found',404);res.json({data:file});}));
 app.get('/api/repositories/:id/commits',wrap((req,res)=>{const r=access(store.read(),req);const depth=z.coerce.number().int().min(1).max(500).parse(req.query.limit??r.settings.historyDepth),offset=z.coerce.number().int().min(0).parse(req.query.offset??0);const branch=req.query.branch?r.branches.find(b=>b.name===req.query.branch):undefined;const ids=branch?ancestors(r,branch.currentHead):null;res.json({data:r.commits.filter(c=>!ids||ids.includes(c.id)).slice(offset,offset+depth)});}));
 app.get('/api/repositories/:id/commits/:commitId',wrap((req,res)=>{const c=access(store.read(),req).commits.find(c=>c.id===req.params.commitId);if(!c)throw new VcsError('Commit not found',404);res.json({data:c});}));
 app.post('/api/repositories/:id/commits',wrap((req,res)=>change(req,res,async(r,s)=>{const started=performance.now();const c=createCommit(r,commitSchema.parse(req.body),currentUser(s,req));await persistObjects(r,storage);r.metrics[r.metrics.length-1].durationMs=performance.now()-started;return c;})));
 app.get('/api/repositories/:id/branches',wrap((req,res)=>res.json({data:access(store.read(),req).branches})));
 app.post('/api/repositories/:id/branches',wrap((req,res)=>change(req,res,(r,s)=>{const input=z.object({name:branchNameSchema,from:z.string().optional()}).parse(req.body);if(r.branches.length>=r.settings.branchLimit)throw new VcsError('Active branch limit reached',409);if(r.branches.some(b=>b.name===input.name))throw new VcsError('Branch already exists',409);const from=input.from?r.branches.find(b=>b.name===input.from):r.branches.find(b=>b.isDefault);if(!from)throw new VcsError('Source branch not found',404);const b={id:randomUUID(),name:input.name,currentHead:from.currentHead,isDefault:false,creatorId:currentUser(s,req).id,createdAt:new Date().toISOString()};r.branches.push(b);addActivity(r,'branch',`Created ${b.name}`,currentUser(s,req).name);return b;})));
 app.patch('/api/repositories/:id/branches/:branchId',wrap((req,res)=>change(req,res,(r,s)=>{const input=z.object({name:branchNameSchema.optional(),isDefault:z.literal(true).optional()}).parse(req.body),b=r.branches.find(b=>b.id===req.params.branchId);if(!b)throw new VcsError('Branch not found',404);if(input.name&&r.branches.some(o=>o.id!==b.id&&o.name===input.name))throw new VcsError('Branch already exists',409);if(input.isDefault)r.branches.forEach(b=>b.isDefault=false);Object.assign(b,input);addActivity(r,'branch',`Updated ${b.name}`,currentUser(s,req).name);return b;},true)));
 app.delete('/api/repositories/:id/branches/:branchId',wrap((req,res)=>change(req,res,(r,s)=>{const b=r.branches.find(b=>b.id===req.params.branchId);if(!b)throw new VcsError('Branch not found',404);if(b.isDefault)throw new VcsError('Cannot delete the default branch',409);r.branches=r.branches.filter(v=>v.id!==b.id);addActivity(r,'branch',`Deleted ${b.name}`,currentUser(s,req).name);return {ok:true};},true)));
 const mergeInput=z.object({source:z.string(),target:z.string()});
 app.post('/api/repositories/:id/merge/check',wrap((req,res)=>{const i=mergeInput.parse(req.body);res.json({data:mergeCheck(access(store.read(),req),i.source,i.target)});}));
 app.post('/api/repositories/:id/merge/fast-forward',wrap((req,res)=>change(req,res,(r,s)=>{const i=mergeInput.parse(req.body);return fastForward(r,i.source,i.target,currentUser(s,req).name);} )));
 app.post('/api/repositories/:id/rebase',wrap((req,res)=>change(req,res,async(r,s)=>{const i=mergeInput.parse(req.body),result=rebase(r,i.source,i.target,currentUser(s,req));await persistObjects(r,storage);return result;})));
 for(const resource of ['performance','activity','members','settings'] as const)app.get(`/api/repositories/:id/${resource}`,wrap((req,res)=>{const r=access(store.read(),req);res.json({data:resource==='performance'?r.metrics:r[resource]});}));
 app.patch('/api/repositories/:id/settings',wrap((req,res)=>change(req,res,(r,s)=>{const settings=settingsSchema.parse({...r.settings,...req.body});if(settings.branchLimit<r.branches.length)throw new VcsError('Branch limit cannot be below the number of active branches');r.settings=settings;addActivity(r,'settings','Updated performance policy',currentUser(s,req).name);return settings;},true)));
 app.post('/api/repositories/:id/members',wrap((req,res)=>change(req,res,(r,s)=>{const input=z.object({email:z.string().email(),role:z.enum(['Maintainer','Developer','Viewer'])}).parse(req.body);const u=s.users.find(u=>u.email===input.email.toLowerCase());if(!u)throw new VcsError('This person must create an account first. Email invitations are not configured.',404);if(r.members.some(m=>m.userId===u.id))throw new VcsError('Already a member',409);const member={id:randomUUID(),userId:u.id,name:u.name,email:u.email,role:input.role};r.members.push(member);addActivity(r,'member',`Added ${u.name} to the team`,currentUser(s,req).name);return member;},true)));
 app.patch('/api/repositories/:id/members/:memberId',wrap((req,res)=>change(req,res,(r)=>{const m=r.members.find(m=>m.id===req.params.memberId);if(!m)throw new VcsError('Member not found',404);if(m.role==='Owner')throw new VcsError('Cannot change the owner role');m.role=z.enum(['Maintainer','Developer','Viewer']).parse(req.body.role);return m;},true)));
 app.delete('/api/repositories/:id/members/:memberId',wrap((req,res)=>change(req,res,(r)=>{const m=r.members.find(m=>m.id===req.params.memberId);if(!m)throw new VcsError('Member not found',404);if(m.role==='Owner')throw new VcsError('Cannot remove the owner');r.members=r.members.filter(m=>m.id!==req.params.memberId);return {ok:true};},true)));
 app.use('/api',(_req,res)=>res.status(404).json({error:'Endpoint not found'}));
 app.use((error:unknown,_req:Request,res:Response,_next:NextFunction)=>{if(error instanceof z.ZodError){res.status(400).json({error:error.issues.map(i=>`${i.path.join('.')}: ${i.message}`).join('; ')});return;}if(error instanceof VcsError){res.status(error.status).json({error:error.message});return;}if(error instanceof SyntaxError){res.status(400).json({error:'Invalid JSON request'});return;}console.error(error);res.status(500).json({error:'The server could not complete this operation. Please retry.'});});return app;
}
