import dotenv from 'dotenv';import {resolve} from 'node:path';import {randomBytes} from 'node:crypto';import {createServer} from 'node:http';import {Server} from 'socket.io';import jwt from 'jsonwebtoken';import {openStore} from './store';import {createApp} from './app';import {MetadataCache} from './cache';
dotenv.config({path:resolve('../../.env')});dotenv.config();
const demo=process.env.DEMO_ENABLED!=='false';const secret=process.env.JWT_SECRET??(process.env.NODE_ENV==='production'?'':randomBytes(48).toString('hex'));if(secret.length<32)throw new Error('JWT_SECRET must contain at least 32 characters');
const store=await openStore({seed:demo});const cache=new MetadataCache();await cache.connect(process.env.REDIS_URL);
const app=createApp(store,{secret,demo,cache,origin:process.env.WEB_ORIGIN,onChange:id=>io.to(id).emit('repository:changed',{id})});const server=createServer(app);const io=new Server(server,{cors:{origin:process.env.WEB_ORIGIN??'http://localhost:5173',credentials:true}});
io.use((socket,next)=>{try{const cookie=socket.handshake.headers.cookie?.split(';').map(s=>s.trim()).find(s=>s.startsWith('velocity_session='))?.split('=')[1];const payload=jwt.verify(cookie??'',secret) as {sub:string;sid:string};if(!store.read().sessions.some(s=>s.id===payload.sid&&new Date(s.expiresAt).getTime()>Date.now()))throw new Error();socket.data.userId=payload.sub;next();}catch{next(new Error('Unauthorized'));}});
io.on('connection',socket=>{for(const repo of store.read().repositories)if(repo.visibility==='public'||repo.members.some(m=>m.userId===socket.data.userId))void socket.join(repo.id);});
server.listen(Number(process.env.PORT??4000),'0.0.0.0',()=>console.log(`Velocity API ready on http://localhost:${process.env.PORT??4000} (Supabase Postgres + Storage)`));
async function shutdown(){io.close();server.close();await cache.close();await store.close();process.exit(0);}process.on('SIGINT',shutdown);process.on('SIGTERM',shutdown);
