import {hashSync} from 'bcryptjs';
import {randomUUID} from 'node:crypto';
import {defaultSettings,type State,type Repository,type User} from '../../../packages/shared/src/index';
import {createCommit,addActivity} from '../../../packages/vcs-core/src/index';
export function makeRepository(name:string,user:User,options:Partial<Repository>={}):Repository {const now=new Date().toISOString();return {id:randomUUID(),name,description:'',visibility:'private',language:'TypeScript',ownerId:user.id,archived:false,createdAt:now,updatedAt:now,branches:[{id:randomUUID(),name:'main',isDefault:true,currentHead:null,creatorId:user.id,createdAt:now},{id:randomUUID(),name:'develop',isDefault:false,currentHead:null,creatorId:user.id,createdAt:now}],commits:[],members:[{id:randomUUID(),userId:user.id,name:user.name,email:user.email,role:'Owner'}],activity:[],metrics:[],settings:{...defaultSettings},...options};}
export function seedState():State {
 const names=['Aarav Mehta','Riya Shah','Kabir Nair','Meera Iyer'];const users=names.map((name,i)=>({id:`user-${i+1}`,name,email:i===0?'demo@velocity.dev':`${name.split(' ')[0].toLowerCase()}@velocity.dev`,passwordHash:hashSync('Velocity2026!',10)}));
 const descriptions=['The frontend that keeps everything moving.','A single entry point for our services.','Reliable payments, without the complexity.','Production inference, made lightweight.','A better experience, wherever you are.'];
 const repositories=['frontend-dashboard','api-gateway','payment-service','ml-inference','mobile-app'].map((name,i)=>{
 const repo=makeRepository(name,users[0],{id:`repo-${i+1}`,description:descriptions[i],language:['TypeScript','Go','TypeScript','Python','Dart'][i],visibility:i===1?'public':'private'});
 repo.members=users.slice(0,i===3?2:4).map((u,j)=>({id:randomUUID(),userId:u.id,name:u.name,email:u.email,role:j===0?'Owner':j===1?'Maintainer':'Developer'}));
 const files:Record<string,string>={'README.md':`# ${name}\n\n${descriptions[i]}\n\n## Getting started\n\nnpm install\nnpm run dev\n\n## Built with Velocity\n\nLess distributed complexity. Faster everyday version control.\n`,'package.json':JSON.stringify({name,version:'1.0.0',private:true,scripts:{dev:'vite',build:'vite build'}},null,2),'.gitignore':'node_modules\ndist\n.env\n','src/App.tsx':`import { useState } from 'react';\n\nexport default function App() {\n  const [count, setCount] = useState(0);\n\n  return (\n    <main className="workspace">\n      <h1>Build something great.</h1>\n      <button onClick={() => setCount(count + 1)}>\n        Shipped {count} improvements\n      </button>\n    </main>\n  );\n}\n`,'src/lib/cache.ts':'const cache = new Map<string, unknown>();\n\nexport const get = (key: string) => cache.get(key);\nexport const set = (key: string, value: unknown) => cache.set(key, value);\n','src/styles.css':':root {\n  color-scheme: dark;\n  --accent: #c5f277;\n}\n','docs/architecture.md':'# Architecture\n\nClient → API → PostgreSQL + Redis → Object storage\n\nOne canonical source of truth.\n'};
 const messages=['chore: initialize workspace','feat: add fast-forward merge checks','chore: archive old snapshots','refactor: optimize status scanner','fix: prevent stale cache reads','feat: add repository analytics'];
 for(let j=0;j<messages.length;j++){const c=createCommit(repo,{message:messages[j],branch:'main',files:j===0?files:{'src/lib/cache.ts':`${files['src/lib/cache.ts']}\n// ${messages[j]}\nexport const revision = ${j};\n`}},users[j%4]);c.createdAt=new Date(Date.now()-(6-j)*3600000-i*5400000).toISOString();repo.activity[0].createdAt=c.createdAt;}
 repo.branches[1].currentHead=repo.branches[0].currentHead;
 for(const name of (i===0?['feature/auth','feature/analytics','hotfix/login']:['feature/core']))repo.branches.push({id:randomUUID(),name,currentHead:repo.branches[0].currentHead,isDefault:false,creatorId:users[1].id,createdAt:new Date().toISOString()});
 if(i===0)createCommit(repo,{message:'feat: add session authentication',branch:'feature/auth',files:{'src/auth.ts':'export const session = { strategy: "httpOnly-cookie" };\n'}},users[1]);
 repo.metrics=[];for(let day=0;day<14;day++)for(const [op,base]of [['status',24],['commit',58],['switch',18],['sync',89]] as const)repo.metrics.push({id:randomUUID(),operation:op,durationMs:base+Math.sin(day*1.6+i)*base*.22,cacheHit:day%7!==0,filesScanned:924,hashesAvoided:891,createdAt:new Date(Date.now()-(13-day)*86400000).toISOString(),simulated:true});
 addActivity(repo,'sync','Synced with canonical server',users[0].name);repo.updatedAt=repo.commits[0].createdAt;return repo;
 });return {users,repositories,sessions:[]};
}
