#!/usr/bin/env node
import {Command} from 'commander';import {readFile,writeFile,mkdir,readdir,stat,rm} from 'node:fs/promises';import {resolve,join,relative,dirname} from 'node:path';import {createInterface} from 'node:readline/promises';import {stdin,stdout} from 'node:process';import type {Repository,Commit,FileRecord} from '../../../packages/shared/src/index';import {fastHash,sha256,metadataUnchanged,validPath} from '../../../packages/vcs-core/src/index';
interface Config {server:string;token:string;repositoryId?:string;branch:string;head:string|null;}
interface IndexEntry {size:number;mtimeMs:number;hash:string;secureHash:string;}
const root=process.cwd(),meta=join(root,'.velocity'),configPath=join(meta,'config.json');
async function json<T>(path:string,fallback:T):Promise<T>{try{return JSON.parse(await readFile(path,'utf8')) as T;}catch(e){if((e as NodeJS.ErrnoException).code==='ENOENT')return fallback;throw e;}}
async function save(name:string,value:unknown){await mkdir(meta,{recursive:true});await writeFile(join(meta,name),JSON.stringify(value,null,2),{mode:0o600});}
async function config(){const c=await json<Config|null>(configPath,null);if(!c)throw new Error('Run velocity login first in this directory.');return c;}
async function request<T>(c:Config,path:string,method='GET',body?:unknown):Promise<T>{const response=await fetch(`${c.server}/api${path}`,{method,headers:{'Content-Type':'application/json',Authorization:`Bearer ${c.token}`},...(body===undefined?{}:{body:JSON.stringify(body)})});const result=await response.json() as {data:T;error:string};if(!response.ok)throw new Error(result.error??`HTTP ${response.status}`);return result.data;}
async function repo(c:Config){if(!c.repositoryId)throw new Error('Run velocity init <repository-id> first.');return request<Repository>(c,`/repositories/${c.repositoryId}`);}
const ignored=new Set(['.velocity','.git','node_modules','dist','coverage','.npm-cache']);
async function scan(){const started=performance.now(),index=await json<Record<string,IndexEntry>>(join(meta,'index.json'),{}),next:Record<string,IndexEntry>={},changed:Record<string,string|null>={};let skipped=0,hashed=0,checked=0;
 async function walk(dir:string){for(const entry of await readdir(dir,{withFileTypes:true})){if(ignored.has(entry.name)||entry.name==='.env'||entry.name.startsWith('.env.')||entry.isSymbolicLink())continue;const path=join(dir,entry.name);if(entry.isDirectory()){await walk(path);continue;}if(!entry.isFile())continue;const name=relative(root,path).replaceAll('\\','/');validPath(name);const metadata=await stat(path);checked++;const old=index[name];if(old&&metadataUnchanged(old,metadata)){next[name]=old;skipped++;continue;}if(metadata.size>2097152)throw new Error(`${name} exceeds the prototype's 2 MiB text-file limit.`);const bytes=await readFile(path);if(bytes.includes(0))throw new Error(`${name} appears binary. The prototype CLI supports UTF-8 text only.`);const content=new TextDecoder('utf-8',{fatal:true}).decode(bytes),hash=fastHash(content),secureHash=sha256(content);hashed++;next[name]={size:metadata.size,mtimeMs:metadata.mtimeMs,hash,secureHash};if(old?.secureHash!==secureHash)changed[name]=content;}}
 await walk(root);for(const name of Object.keys(index))if(!next[name])changed[name]=null;return {changed,next,checked,skipped,hashed,durationMs:performance.now()-started};}
async function restore(c:Config,branch:string){const r=await repo(c),b=r.branches.find(b=>b.name===branch);if(!b)throw new Error('Branch not found');const result=await scan();if(Object.keys(result.changed).length)throw new Error('Working tree has changes. Commit or move them before switching/pulling.');const files=r.commits.find(v=>v.id===b.currentHead)?.files??{},previous=await json<Record<string,IndexEntry>>(join(meta,'index.json'),{});for(const name of Object.keys(files)){validPath(name);const path=resolve(root,name);if(!path.startsWith(root+requireSeparator()))throw new Error('Path escapes workspace');await mkdir(dirname(path),{recursive:true});await writeFile(path,files[name].content);}for(const name of Object.keys(previous))if(!files[name]){validPath(name);const path=resolve(root,name);if(!path.startsWith(root+requireSeparator()))throw new Error('Path escapes workspace');await rm(path,{force:true});}const next:Record<string,IndexEntry>={};for(const [name,f]of Object.entries(files)){const s=await stat(join(root,name));next[name]={size:s.size,mtimeMs:s.mtimeMs,hash:f.fastHash,secureHash:f.secureHash};}await save('index.json',next);await save('config.json',{...c,branch,head:b.currentHead});await save('history.json',r.commits.slice(0,r.settings.historyDepth));await writeFile(join(meta,'HEAD'),branch);console.log(`On ${branch} · ${Object.keys(files).length} files restored`);}
function requireSeparator(){return process.platform==='win32'?'\\':'/';}
const program=new Command().name('velocity').description('Focused, canonical-server version control').version('1.0.0');
program.command('login').option('--server <url>','Velocity API URL','http://localhost:4000').option('--email <email>').option('--password <password>','Prefer interactive input or VELOCITY_PASSWORD').action(async options=>{const rl=createInterface({input:stdin,output:stdout});try{const email=options.email??await rl.question('Email: ');const password=options.password??process.env.VELOCITY_PASSWORD??await rl.question('Password (input is visible): ');const server=String(options.server).replace(/\/$/,'');const previous=await json<Config|null>(configPath,null);const user=await request<{token:string;name:string}>({server,token:'',branch:'main',head:null},'/auth/login','POST',{email,password,cli:true});await save('config.json',{...previous,server,token:user.token,branch:previous?.branch??'main',head:previous?.head??null});console.log(`Signed in as ${user.name}`);}finally{rl.close();}});
program.command('init <repository-id>').action(async repositoryId=>{const c=await config();if(c.repositoryId&&c.repositoryId!==repositoryId)throw new Error('This directory is already linked. Use a new directory for another repository.');const r=await request<Repository>(c,`/repositories/${repositoryId}`),branch=r.branches.find(b=>b.isDefault)!.name;await save('config.json',{...c,repositoryId,branch,head:null});await mkdir(join(meta,'cache'),{recursive:true});await mkdir(join(meta,'objects'),{recursive:true});await writeFile(join(meta,'HEAD'),branch);console.log(`Initialized ${r.name}. Run velocity pull in an otherwise empty directory.`);});
program.command('status').action(async()=>{const c=await config(),s=await scan();console.log(`Branch: ${c.branch}\n${s.checked} files checked · ${s.skipped} metadata skips · ${s.hashed} hashed\n${Object.keys(s.changed).length} changes\n${s.durationMs.toFixed(2)}ms (measured locally)`);for(const [p,v]of Object.entries(s.changed))console.log(`${v===null?'D':'M'} ${p}`);});
program.command('add [path]').description('Stage all changes; only . is supported').action(async(path='.')=>{if(path!=='.')throw new Error('Use velocity add . in this prototype');await config();const s=await scan();await save('staged.json',s.changed);console.log(`${Object.keys(s.changed).length} file changes staged`);});
program.command('commit').requiredOption('-m, --message <message>').action(async options=>{const c=await config();await repo(c);const files=await json<Record<string,string|null>|null>(join(meta,'staged.json'),null);if(!files||!Object.keys(files).length)throw new Error('No staged changes. Run velocity add .');const s=await scan();for(const [path,content]of Object.entries(files))if((s.changed[path]??null)!==content)throw new Error(`${path} changed after staging. Run velocity add . again.`);const commit=await request<Commit>(c,`/repositories/${c.repositoryId}/commits`,'POST',{message:options.message,branch:c.branch,expectedHead:c.head,files});const index=await json<Record<string,IndexEntry>>(join(meta,'index.json'),{});for(const path of Object.keys(files)){if(s.next[path])index[path]=s.next[path];else delete index[path];}await save('index.json',index);await save('staged.json',{});await save('config.json',{...c,head:commit.id});console.log(`[${c.branch} ${commit.shortHash}] ${commit.message}\nSaved to canonical server; no extra push needed.`);});
program.command('log').option('--older <offset>','Fetch older history offset','0').action(async options=>{const c=await config();await repo(c);const commits=await request<Commit[]>(c,`/repositories/${c.repositoryId}/commits?branch=${encodeURIComponent(c.branch)}&offset=${Number(options.older)}`);for(const v of commits)console.log(`${v.shortHash}  ${v.message}  (${v.author})`);});
program.command('branch [name]').action(async name=>{const c=await config(),r=await repo(c);if(!name){r.branches.forEach(b=>console.log(`${b.name===c.branch?'*':' '} ${b.name}`));return;}await request(c,`/repositories/${c.repositoryId}/branches`,'POST',{name,from:c.branch});console.log(`Created ${name}`);});
program.command('switch <branch>').action(async branch=>restore(await config(),branch));
program.command('pull').action(async()=>{const c=await config();await restore(c,c.branch);});
program.command('push').action(async()=>{await repo(await config());console.log('Commits are saved directly to the canonical server. There is no separate push queue.');});
program.command('rebase <target>').action(async target=>{const c=await config();if(Object.keys((await scan()).changed).length)throw new Error('Commit changes before rebasing');await request(c,`/repositories/${c.repositoryId}/rebase`,'POST',{source:c.branch,target});await restore(c,c.branch);});
program.parseAsync().catch((error:Error)=>{console.error(`Velocity: ${error.message}`);process.exitCode=1;});
